### ISSUE TITLE
Cannot start IElixir kernel

### ISSUE THREAD

**Issue by nicbet** [SaschaJust/docker-datascience#2]
### 1. Run Docker container
`docker run --rm -it -p 8888:8888 sjust/jupyter-datascience:latest bash`

### 2. Start Jupyter
`jupyter notebook --ip=0.0.0.0 --port=8888`

### 3. Login to Jupyter and create a new Elixir kernel

```
[I 03:13:49.183 NotebookApp] Creating new notebook in /work
[I 03:13:49.195 NotebookApp] Writing notebook-signing key to /home/datascience/.local/share/jupyter/notebook_secret
[I 03:13:50.077 NotebookApp] Kernel started: 4e39c7ee-5452-4d59-842d-b0c8b3ecbd1f
warning: found quoted keyword "coveralls" but the quotes are not required. Note that keywords are always atoms, even when quoted, and quotes should only be used to introduce keywords with foreign characters in them
  mix.exs:21

** (File.Error) could not remove files and directories recursively from "/opt/ielixir-0.9.13/_build/prod/lib/ielixir/priv": permission denied
    (elixir) lib/file.ex:1189: File.rm_rf!/1
    (mix) lib/mix/project.ex:593: Mix.Project.symlink_or_copy/3
    (mix) lib/mix/project.ex:586: Mix.Project.build_structure/2
    (mix) lib/mix/tasks/compile.all.ex:20: Mix.Tasks.Compile.All.run/1
    (mix) lib/mix/task.ex:316: Mix.Task.run_task/3
    (mix) lib/mix/tasks/compile.ex:94: Mix.Tasks.Compile.run/1
    (mix) lib/mix/task.ex:316: Mix.Task.run_task/3
    (mix) lib/mix/tasks/app.start.ex:57: Mix.Tasks.App.Start.run/1
```

**Comment by SaschaJust** [comment]
Fixed in 493af20a9b4d5e3661ee3dcf339e649eb0dd5237.
